# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true
        
    - name: Build for Debian
      working-directory: server
      run: GOOS=linux GOARCH=amd64 go build -o yt-info-to-obs

    - name: Build for Windows
      working-directory: server
      run: GOOS=windows GOARCH=amd64 go build -o yt-info-to-obs.exe

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          yt-info-to-obs
          yt-info-to-obs.exe
    
